import logging

from Node import Node

f = open("fcfs_aar.txt", "w")
f_cpu = open("fcfs_cpu.txt", "w")
f_ram = open("fcfs_ram.txt", "w")
f_sto = open("fcfs_storage.txt", "w")
f_as = open("fcfs_active-slices.txt", "w")
f_revenue_time = open("fcfs_revenue-time.txt", "w")

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s\t%(message)s')


system_capacity = list()


def FCFS(NSRs, max_slots, sample_pool, total_requests):
    global system_capacity

    S1 = Node(1, 1, 100, 100, 100)

    system_capacity = [S1[2], S1[3], S1[4]]  # Cloud
    # print("System Capacity: ", system_capacity, " Aggregated Capacity: ", aggregated_system_capacity)

    # E1 = [nodeCPU(), nodeRAM(), nodeSto()]  # Edge 1
    # E2 = [nodeCPU(), nodeRAM(), nodeSto()]  # Edge 2
    # E3 = [nodeCPU(), nodeRAM(), nodeSto()]  # Edge 3
    # E4 = [nodeCPU(), nodeRAM(), nodeSto()]  # Edge 4
    # R1 = [nodeCPU(), nodeRAM(), nodeSto()]  # RU 1
    # R2 = [nodeCPU(), nodeRAM(), nodeSto()]  # RU 2
    # R3 = [nodeCPU(), nodeRAM(), nodeSto()]  # RU 3

    overall_system_util = [0, 0, 0]
    total_util = 0
    no_accepted = 0
    # no_rejected = 0
    # all_revenues = 0
    # sum_sl_lifetime = 0
    accumulated_value = 0
    accumulated_squares = 0
    slot = 0
    request_accumulator = 0
    accepted_requests = {}
    expired_slices = []

    while slot < max_slots:
        NSRs_in_current_slot = []

        number_of_requests_in_slot = NSRs[slot]

        first_sub_idx = request_accumulator
        last_sub_idx = request_accumulator + number_of_requests_in_slot

        for sub_idx in range(first_sub_idx, last_sub_idx):
            NSRs_in_current_slot.append(sample_pool[sub_idx])

        request_accumulator += number_of_requests_in_slot

        # print("#######################################################################################################")
        # print("Time Slot: ", slot)
        # print(len(NSRs_in_current_slot), " NSRs in Current Timeslot: ", NSRs_in_current_slot)
        # print("#######################################################################################################")
        # This is every request that is generated by system - can be accepted or rejected, active or expired.

        for request in NSRs_in_current_slot:
            request_value = request[4]
            # all_revenues += request_value

            # print("###################################################################################################")
            # print("NSR: ", slot, ":", a)
            # print("###################################################################################################")
            # print("Current Slice Request: ", append_slot_req)
            # print("Slice Request Value: ", round(v_i, 1))
            # print("")
            # print("CPU utilization: ", node_cpu_util)
            # print("RAM utilization: ", node_ram_util)
            # print("Storage utilization: ", sto_node_util)

            current_available_system_resources = list(map(lambda x, y: x - y, system_capacity, overall_system_util))
            # print("Current Availability before decision: ", list(np.around(np.array(system_current_available_resources), 2)))

            if all(x < y for x, y in zip(request[0:3], current_available_system_resources)):
                # print("Request Accepted")
                no_accepted += 1

                accepted_requests[no_accepted] = [*request, slot]
                accumulated_value += request_value
                accumulated_squares += request_value ** 2
                # active_slices = [s for s in accepted_requests if s not in expired_slices]
                # print("Number of Active Slices: ", len(active_slices))

                # if request[3] == 's1':
                #     s1 += 1
                # elif request[2] == 's2':
                #     s2 += 1
                # elif request[2] == 's3':
                #     s3 += 1

                # sum_sl_lifetime += request[3]

                overall_system_util[0] += request[0]
                overall_system_util[1] += request[1]
                overall_system_util[2] += request[2]

            # Slice Request is Rejected - Slice CNF Requirements are larger than the available requirements.
            # else:
                # print("Request Rejected")
                # no_rejected += 1

                # active_slices = [s for s in accepted_requests if s not in expired_slices]
                # print("Number of Active Slices: ", len(active_slices))

        # Used to track the expired requests
        expired_requests = []
        # Check for expired slices in the requests list
        for old_request in accepted_requests:
            if slot == accepted_requests[old_request][3] + accepted_requests[old_request][5]:  # reqs_[5] + reqs_[6]
                expired_requests.append(old_request)
                overall_system_util[0] -= accepted_requests[old_request][0]
                overall_system_util[1] -= accepted_requests[old_request][1]
                overall_system_util[2] -= accepted_requests[old_request][2]

        # Remove expired slices from the accepted requests dict
        for expired_request_idx in expired_requests:
            del accepted_requests[expired_request_idx]

        slot += 1
        total_util += sum(overall_system_util)

        current_acceptance_ratio = float(no_accepted) / total_requests
        # print("Current Acceptance Ratio: ", current_acceptance_ratio)
        # curr_rej = round(no_rejected / total_requests, 3)
        # curr_req = round(no_requested / total_requests, 3)
        # curr_avail = round(sum_cpu / total_requests, 3)

        # f.write(str(current_acceptance_ratio) + ',' + str(slot) + '\n')
        # print("Current Acceptance Ratio: ", curr_acr)
        # print(" ")

        # cpu_util = round((sum([nodeCPU() - node[0]]) / nodeCPU()) * 100, 3)
        # f_cpu.write(str(round(overall_system_util[0] / system_capacity[0], 2)) + ',' + str(slot) + '\n')

        # ram_util = round((sum([nodeRAM() - node[1]]) / nodeRAM()) * 100, 3)
        # f_ram.write(str(round(overall_system_util[1] / system_capacity[1], 2)) + ',' + str(slot) + '\n')

        # sto_util = round((sum([nodeSto() - node[2]]) / nodeSto()) * 100, 3)
        # f_sto.write(str(round(overall_system_util[2] / system_capacity[2], 2)) + ',' + str(slot) + '\n')

        # f_revenue_time.write(str(round(accumulated_value, 2)) + ',' + str(slot) + '\n')

        # f_as.write(str(len(set(accepted).difference(expired_slices))) + ',' + str(slot) + '\n')

    # f.close()
    # f_cpu.close()
    # f_ram.close()
    # f_sto.close()
    # f_revenue_time.close()
    # f_as.close()
    # print("###########################################################################################################")
    # print("###########################################################################################################")
    # print("Number of Requests: ", sum(NSRs))
    print("Number of Accepted Requests: ", no_accepted)
    # print("Number of Rejected Requests: ", no_rejected)
    # print("Final Acceptance Ratio: ", round(no_accepted / sum(NSRs), 3))
    # print("Number of Accepted BE Slices: ", no_be)
    # print("Number of Accepted URLLC Slices: ", no_urllc)
    # print("Number of Accepted eMBB Slices: ", no_embb)
    # print("Average CPU Utilization (%): ", round(avg_cpu / C[0], 2))
    # print("Average RAM Utilization (%): ", round(avg_ram / C[1], 2))
    # print("Average Storage Utilization (%): ", round(avg_sto / C[2], 2))
    # print("Average Slice life time: ", round(sum_sl_lifetime / no_accepted, 1))
    # active_slices = [s for s in accepted_requests if s not in expired_slices]
    # print("Number of Active Slices at end of Simulation: ", len(active_slices))
    # print("Number of Expired Slices at end of Simulation: ", len(expired_slices))
    # print("Number of Active Slices: ", len(set(accepted).difference(expired_slices)))
    # print("Number of Expired Slices: ", len(expired_slices))
    # print("Active Slices: ", sorted(set(accepted).difference(expired_slices)))
    # print("Total Value of Accepted SRs: ", round(accumulated_value))
    # print("Total Value of All SRs: ", round(all_revenues))
    # print("Ratio - Accepted Values/Total Value: ", round(accumulated_value / all_revenues, 3))
    # print("Average Value of Accepted Slices: ", round(accumulated_value / len(accepted_requests)))
    # print("Max Value: ", round(max(all_revenues)))
    # print("Min Value: ", round(min(all_revenues)))

    #############################################################################################################
    #############################################################################################################
    # a_ = np.genfromtxt("linrp_cpu.txt", delimiter=",", dtype=np.float64)
    # print("###################")
    # print("CPU")
    # c_ = loadtxt("fcfs_cpu.txt", comments="#", delimiter=",", unpack=False, dtype=np.float64)
    # c = c_[:, 0]
    # cpu_mean = np.mean(c)
    # cpu_std = np.std(c)
    # cpu_upper = cpu_mean + cpu_std
    # cpu_lower = cpu_mean - cpu_std
    # print(cpu_upper)
    # print(round(cpu_mean, 3))
    # print(cpu_lower)
    # print("###################")
    #############################################################################################################
    #############################################################################################################
    # a_ = np.genfromtxt("linrp_cpu.txt", delimiter=",", dtype=np.float64)
    # print("RAM")
    # r_ = loadtxt("fcfs_ram.txt", comments="#", delimiter=",", unpack=False, dtype=np.float64)
    # r = r_[:, 0]
    # ram_mean = np.mean(r)
    # ram_std = np.std(r)
    # ram_upper = ram_mean + ram_std
    # ram_lower = ram_mean - ram_std
    # print(ram_upper)
    # print(round(ram_mean, 3))
    # print(ram_lower)
    #############################################################################################################
    #############################################################################################################
    # a_ = np.genfromtxt("linrp_cpu.txt", delimiter=",", dtype=np.float64)
    # print("###################")
    # s_ = loadtxt("fcfs_storage.txt", comments="#", delimiter=",", unpack=False, dtype=np.float64)
    # print("Storage")
    # s = s_[:, 0]
    # sto_mean = np.mean(s)
    # sto_std = np.std(s)
    # sto_upper = sto_mean + sto_std
    # sto_lower = sto_mean - sto_std
    # print(sto_upper)
    # print(round(sto_mean, 3))
    # print(sto_lower)
    # print("###################")

    return float(accumulated_value), float(no_accepted), float(total_util), float(accumulated_squares)

#############################################################################################################
#############################################################################################################
def main(max_slots, fixed_NSRs, sample_pool, total_requests):

    return FCFS(fixed_NSRs, max_slots, sample_pool, total_requests)

    # Average Acceptance Ratio
    # aar()
    # # Utilization over time times
    # cpu()
    # ram()
    # storage()
    # fcfs_as()
    # all_cpu()
    # all_mem()
    # all_sto()
    # cpu_req_()
    # ram_req_()
    # sto_req_()

